plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs

packageExtensions:
  "@chakra-ui/checkbox@*":
    dependencies:
      "framer-motion": "*"
  "@chakra-ui/styled-system@*":
    dependencies:
      lodash.mergewith: ^4.6.2
  "@chakra-ui/icon@*":
    dependencies:
      "@chakra-ui/system": "*"
  "@chakra-ui/system@*":
    dependencies:
      "@emotion/react": "*"
      "@emotion/styled": "*"
  "@chakra-ui/transition@*":
    dependencies:
      framer-motion: "*"